version: '3.4'

services:
  starcitizen.eshop.webapi:
    image: ${DOCKER_REGISTRY-}starcitizeneshopwebapi
    build:
      context: .
      dockerfile: StarCitizen.eShop.WebApi/Dockerfile
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sqlserver
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password